contact:
    resource: "@ContactBundle/Resources/config/routing.yml"
    prefix:   /

galerie:
    resource: "@GalerieBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

gite:
    resource: "@GiteBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
