galerie:
    resource: "@GalerieBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

gite:
    resource: "@GiteBundle/Resources/config/routing.yml"
    prefix:   /
