galerie:
    resource: "@GalerieBundle/Resources/config/routing.yml"
    prefix:   /

image:
    resource: "@ImageBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

reservation:
    resource: "@ReservationBundle/Resources/config/routing.yml"
    prefix:   /

gite:
    resource: "@GiteBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@mainBundle/Resources/config/routing.yml"
    prefix:   /

image:
    resource: "@ImageBundle/Resources/config/routing.yml"
    prefix:   /

galerie:
    resource: "@GalerieBundle/Resources/config/routing.yml"
    prefix:   /
