home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

reservation:
    resource: "@ReservationBundle/Resources/config/routing.yml"
    prefix:   /

gite:
    resource: "@GiteBundle/Resources/config/routing.yml"
    prefix:   /
