gite_gite:
    resource: "@GiteBundle/Resources/config/routing/gite.yml"
    prefix:   /dash/gite

gite_reservation:
    resource: "@GiteBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

gite_view:
    path:     /gite/{id}/
    defaults: { _controller: GiteBundle:Gite:getGite }

gite_listview:
    path:     /gites/
    defaults: { _controller: GiteBundle:Gite:getListGites }