gite_view:
    path:     /gite/{id}/
    defaults: { _controller: GiteBundle:Gite:getGite }

gite_listview:
    path:     /gites/
    defaults: { _controller: GiteBundle:Gite:ListGites }

new_gite:
    path:     /newgite/
    defaults: { _controller: GiteBundle:Gite:newGite}

pre_reservation_new:
    path:     /gite/{id}/pre-reservation/
    defaults: { _controller: GiteBundle:Reservation:newPreReservation }

reservation_new:
    path:     /gite/{id}/reservation/
    defaults: { _controller: GiteBundle:Reservation:newReservation }
