gite_view:
    path:     /gite/{id}/
    defaults: { _controller: GiteBundle:Gite:getGite }

gite_listview:
    path:     /gites/
    defaults: { _controller: GiteBundle:Gite:ListGites }

new_gite:
    path:     /newgite/
    defaults: { _controller: GiteBundle:Gite:newGite}

reservation_create:
    path:     /gite/{id}/reservation/
    defaults: { _controller: GiteBundle:Reservation:createReservation }
