gite_view:
    path:     /gite/{id}/
    defaults: { _controller: GiteBundle:Gite:getGite }

gite_listview:
    path:     /gites/
    defaults: { _controller: GiteBundle:Gite:getGiteList }

reservation_create:
    path:     /gite/{id}/reservation/
    defaults: { _controller: GiteBundle:Reservation:createReservation }
