<?php

namespace Gite\GiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiteRepository extends EntityRepository
{
}
