<?php

namespace Gite\GalerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieRepository extends EntityRepository
{
}
